// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProfitColumns holds the columns for the "profit" table.
	ProfitColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "DATETIME"}},
		{Name: "profit", Type: field.TypeJSON, Nullable: true},
	}
	// ProfitTable holds the schema information for the "profit" table.
	ProfitTable = &schema.Table{
		Name:       "profit",
		Columns:    ProfitColumns,
		PrimaryKey: []*schema.Column{ProfitColumns[0]},
	}
	// TradelogColumns holds the columns for the "tradelog" table.
	TradelogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "DATETIME"}},
		{Name: "exchange", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "VARCHAR(200)"}},
		{Name: "ticker", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "VARCHAR(200)"}},
		{Name: "position", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "VARCHAR(200)"}},
		{Name: "strategy", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "VARCHAR(200)"}},
		{Name: "price", Type: field.TypeFloat64, Nullable: true},
		{Name: "quantity", Type: field.TypeFloat64, Nullable: true},
		{Name: "leverage", Type: field.TypeInt, Nullable: true},
	}
	// TradelogTable holds the schema information for the "tradelog" table.
	TradelogTable = &schema.Table{
		Name:       "tradelog",
		Columns:    TradelogColumns,
		PrimaryKey: []*schema.Column{TradelogColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProfitTable,
		TradelogTable,
	}
)

func init() {
	ProfitTable.Annotation = &entsql.Annotation{
		Table: "profit",
	}
	TradelogTable.Annotation = &entsql.Annotation{
		Table: "tradelog",
	}
}
