// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Profit is the predicate function for profit builders.
type Profit func(*sql.Selector)

// TradeLog is the predicate function for tradelog builders.
type TradeLog func(*sql.Selector)
