version: '2'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379", "--requirepass", "mypassword"]
    # command: redis-server --requirepass mypassword
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - "15214:6379"

  trade_control:
    build:
      context: .
      dockerfile: ./docker/premium_backend/Dockerfile
    ports:
      - "10532:10532"
    depends_on:
      - redis
    healthcheck:
      test: curl --fail http://0.0.0.0:10532/ping || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  premium_band:
    build: 
      context: .
      dockerfile: ./docker/premium_band/Dockerfile
    ports: 
      - "8081:8081"
    depends_on:
      trade_control:
        condition: service_healthy
    restart: unless-stopped

  premium_value:
    build: 
      context: .
      dockerfile: ./docker/premium_value/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      trade_control:
        condition: service_healthy

  premium_trade:
    build:
      context: .
      dockerfile: ./docker/premium_trade/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      trade_control:
        condition: service_healthy

  premium_notice:
    build:
      context: .
      dockerfile: ./docker/premium_notice/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      trade_control:
        condition: service_healthy
    restart: unless-stopped
    
volumes:
  redis_data: