version: '3'
services:
  premium_band:
    build: 
      context: .
      dockerfile: ./docker/premium_band/Dockerfile
    ports: 
      - "8081:8081"
  premium_value:
    build: 
      context: .
      dockerfile: ./docker/premium_value/Dockerfile
    ports:
      - "8082:8082"