// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kimchi/ent/profit"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfitCreate is the builder for creating a Profit entity.
type ProfitCreate struct {
	config
	mutation *ProfitMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (pc *ProfitCreate) SetDate(t time.Time) *ProfitCreate {
	pc.mutation.SetDate(t)
	return pc
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (pc *ProfitCreate) SetNillableDate(t *time.Time) *ProfitCreate {
	if t != nil {
		pc.SetDate(*t)
	}
	return pc
}

// SetProfit sets the "profit" field.
func (pc *ProfitCreate) SetProfit(f []float64) *ProfitCreate {
	pc.mutation.SetProfit(f)
	return pc
}

// SetID sets the "id" field.
func (pc *ProfitCreate) SetID(i int) *ProfitCreate {
	pc.mutation.SetID(i)
	return pc
}

// Mutation returns the ProfitMutation object of the builder.
func (pc *ProfitCreate) Mutation() *ProfitMutation {
	return pc.mutation
}

// Save creates the Profit in the database.
func (pc *ProfitCreate) Save(ctx context.Context) (*Profit, error) {
	var (
		err  error
		node *Profit
	)
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProfitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Profit)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ProfitMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProfitCreate) SaveX(ctx context.Context) *Profit {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProfitCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProfitCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProfitCreate) check() error {
	return nil
}

func (pc *ProfitCreate) sqlSave(ctx context.Context) (*Profit, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (pc *ProfitCreate) createSpec() (*Profit, *sqlgraph.CreateSpec) {
	var (
		_node = &Profit{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: profit.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: profit.FieldID,
			},
		}
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.Date(); ok {
		_spec.SetField(profit.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := pc.mutation.Profit(); ok {
		_spec.SetField(profit.FieldProfit, field.TypeJSON, value)
		_node.Profit = value
	}
	return _node, _spec
}

// ProfitCreateBulk is the builder for creating many Profit entities in bulk.
type ProfitCreateBulk struct {
	config
	builders []*ProfitCreate
}

// Save creates the Profit entities in the database.
func (pcb *ProfitCreateBulk) Save(ctx context.Context) ([]*Profit, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Profit, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProfitCreateBulk) SaveX(ctx context.Context) []*Profit {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProfitCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProfitCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
