// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kimchi/ent/predicate"
	"kimchi/ent/profit"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProfitUpdate is the builder for updating Profit entities.
type ProfitUpdate struct {
	config
	hooks    []Hook
	mutation *ProfitMutation
}

// Where appends a list predicates to the ProfitUpdate builder.
func (pu *ProfitUpdate) Where(ps ...predicate.Profit) *ProfitUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetDate sets the "date" field.
func (pu *ProfitUpdate) SetDate(t time.Time) *ProfitUpdate {
	pu.mutation.SetDate(t)
	return pu
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (pu *ProfitUpdate) SetNillableDate(t *time.Time) *ProfitUpdate {
	if t != nil {
		pu.SetDate(*t)
	}
	return pu
}

// ClearDate clears the value of the "date" field.
func (pu *ProfitUpdate) ClearDate() *ProfitUpdate {
	pu.mutation.ClearDate()
	return pu
}

// SetProfit sets the "profit" field.
func (pu *ProfitUpdate) SetProfit(f []float64) *ProfitUpdate {
	pu.mutation.SetProfit(f)
	return pu
}

// AppendProfit appends f to the "profit" field.
func (pu *ProfitUpdate) AppendProfit(f []float64) *ProfitUpdate {
	pu.mutation.AppendProfit(f)
	return pu
}

// ClearProfit clears the value of the "profit" field.
func (pu *ProfitUpdate) ClearProfit() *ProfitUpdate {
	pu.mutation.ClearProfit()
	return pu
}

// Mutation returns the ProfitMutation object of the builder.
func (pu *ProfitUpdate) Mutation() *ProfitMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProfitUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProfitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProfitUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProfitUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProfitUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProfitUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   profit.Table,
			Columns: profit.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: profit.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Date(); ok {
		_spec.SetField(profit.FieldDate, field.TypeTime, value)
	}
	if pu.mutation.DateCleared() {
		_spec.ClearField(profit.FieldDate, field.TypeTime)
	}
	if value, ok := pu.mutation.Profit(); ok {
		_spec.SetField(profit.FieldProfit, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedProfit(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, profit.FieldProfit, value)
		})
	}
	if pu.mutation.ProfitCleared() {
		_spec.ClearField(profit.FieldProfit, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ProfitUpdateOne is the builder for updating a single Profit entity.
type ProfitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfitMutation
}

// SetDate sets the "date" field.
func (puo *ProfitUpdateOne) SetDate(t time.Time) *ProfitUpdateOne {
	puo.mutation.SetDate(t)
	return puo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (puo *ProfitUpdateOne) SetNillableDate(t *time.Time) *ProfitUpdateOne {
	if t != nil {
		puo.SetDate(*t)
	}
	return puo
}

// ClearDate clears the value of the "date" field.
func (puo *ProfitUpdateOne) ClearDate() *ProfitUpdateOne {
	puo.mutation.ClearDate()
	return puo
}

// SetProfit sets the "profit" field.
func (puo *ProfitUpdateOne) SetProfit(f []float64) *ProfitUpdateOne {
	puo.mutation.SetProfit(f)
	return puo
}

// AppendProfit appends f to the "profit" field.
func (puo *ProfitUpdateOne) AppendProfit(f []float64) *ProfitUpdateOne {
	puo.mutation.AppendProfit(f)
	return puo
}

// ClearProfit clears the value of the "profit" field.
func (puo *ProfitUpdateOne) ClearProfit() *ProfitUpdateOne {
	puo.mutation.ClearProfit()
	return puo
}

// Mutation returns the ProfitMutation object of the builder.
func (puo *ProfitUpdateOne) Mutation() *ProfitMutation {
	return puo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProfitUpdateOne) Select(field string, fields ...string) *ProfitUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Profit entity.
func (puo *ProfitUpdateOne) Save(ctx context.Context) (*Profit, error) {
	var (
		err  error
		node *Profit
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProfitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, puo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Profit)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ProfitMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProfitUpdateOne) SaveX(ctx context.Context) *Profit {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProfitUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProfitUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProfitUpdateOne) sqlSave(ctx context.Context) (_node *Profit, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   profit.Table,
			Columns: profit.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: profit.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Profit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profit.FieldID)
		for _, f := range fields {
			if !profit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Date(); ok {
		_spec.SetField(profit.FieldDate, field.TypeTime, value)
	}
	if puo.mutation.DateCleared() {
		_spec.ClearField(profit.FieldDate, field.TypeTime)
	}
	if value, ok := puo.mutation.Profit(); ok {
		_spec.SetField(profit.FieldProfit, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedProfit(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, profit.FieldProfit, value)
		})
	}
	if puo.mutation.ProfitCleared() {
		_spec.ClearField(profit.FieldProfit, field.TypeJSON)
	}
	_node = &Profit{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
