// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kimchi/ent/predicate"
	"kimchi/ent/tradelog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TradeLogDelete is the builder for deleting a TradeLog entity.
type TradeLogDelete struct {
	config
	hooks    []Hook
	mutation *TradeLogMutation
}

// Where appends a list predicates to the TradeLogDelete builder.
func (tld *TradeLogDelete) Where(ps ...predicate.TradeLog) *TradeLogDelete {
	tld.mutation.Where(ps...)
	return tld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tld *TradeLogDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tld.hooks) == 0 {
		affected, err = tld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TradeLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tld.mutation = mutation
			affected, err = tld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tld.hooks) - 1; i >= 0; i-- {
			if tld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tld *TradeLogDelete) ExecX(ctx context.Context) int {
	n, err := tld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tld *TradeLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tradelog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tradelog.FieldID,
			},
		},
	}
	if ps := tld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// TradeLogDeleteOne is the builder for deleting a single TradeLog entity.
type TradeLogDeleteOne struct {
	tld *TradeLogDelete
}

// Exec executes the deletion query.
func (tldo *TradeLogDeleteOne) Exec(ctx context.Context) error {
	n, err := tldo.tld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tradelog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tldo *TradeLogDeleteOne) ExecX(ctx context.Context) {
	tldo.tld.ExecX(ctx)
}
