// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kimchi/ent/tradelog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TradeLogCreate is the builder for creating a TradeLog entity.
type TradeLogCreate struct {
	config
	mutation *TradeLogMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (tlc *TradeLogCreate) SetDate(t time.Time) *TradeLogCreate {
	tlc.mutation.SetDate(t)
	return tlc
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillableDate(t *time.Time) *TradeLogCreate {
	if t != nil {
		tlc.SetDate(*t)
	}
	return tlc
}

// SetExchange sets the "exchange" field.
func (tlc *TradeLogCreate) SetExchange(s string) *TradeLogCreate {
	tlc.mutation.SetExchange(s)
	return tlc
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillableExchange(s *string) *TradeLogCreate {
	if s != nil {
		tlc.SetExchange(*s)
	}
	return tlc
}

// SetTicker sets the "ticker" field.
func (tlc *TradeLogCreate) SetTicker(s string) *TradeLogCreate {
	tlc.mutation.SetTicker(s)
	return tlc
}

// SetNillableTicker sets the "ticker" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillableTicker(s *string) *TradeLogCreate {
	if s != nil {
		tlc.SetTicker(*s)
	}
	return tlc
}

// SetPosition sets the "position" field.
func (tlc *TradeLogCreate) SetPosition(s string) *TradeLogCreate {
	tlc.mutation.SetPosition(s)
	return tlc
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillablePosition(s *string) *TradeLogCreate {
	if s != nil {
		tlc.SetPosition(*s)
	}
	return tlc
}

// SetStrategy sets the "strategy" field.
func (tlc *TradeLogCreate) SetStrategy(s string) *TradeLogCreate {
	tlc.mutation.SetStrategy(s)
	return tlc
}

// SetNillableStrategy sets the "strategy" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillableStrategy(s *string) *TradeLogCreate {
	if s != nil {
		tlc.SetStrategy(*s)
	}
	return tlc
}

// SetPrice sets the "price" field.
func (tlc *TradeLogCreate) SetPrice(f float64) *TradeLogCreate {
	tlc.mutation.SetPrice(f)
	return tlc
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillablePrice(f *float64) *TradeLogCreate {
	if f != nil {
		tlc.SetPrice(*f)
	}
	return tlc
}

// SetQuantity sets the "quantity" field.
func (tlc *TradeLogCreate) SetQuantity(f float64) *TradeLogCreate {
	tlc.mutation.SetQuantity(f)
	return tlc
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillableQuantity(f *float64) *TradeLogCreate {
	if f != nil {
		tlc.SetQuantity(*f)
	}
	return tlc
}

// SetLeverage sets the "leverage" field.
func (tlc *TradeLogCreate) SetLeverage(i int) *TradeLogCreate {
	tlc.mutation.SetLeverage(i)
	return tlc
}

// SetNillableLeverage sets the "leverage" field if the given value is not nil.
func (tlc *TradeLogCreate) SetNillableLeverage(i *int) *TradeLogCreate {
	if i != nil {
		tlc.SetLeverage(*i)
	}
	return tlc
}

// SetID sets the "id" field.
func (tlc *TradeLogCreate) SetID(i int) *TradeLogCreate {
	tlc.mutation.SetID(i)
	return tlc
}

// Mutation returns the TradeLogMutation object of the builder.
func (tlc *TradeLogCreate) Mutation() *TradeLogMutation {
	return tlc.mutation
}

// Save creates the TradeLog in the database.
func (tlc *TradeLogCreate) Save(ctx context.Context) (*TradeLog, error) {
	var (
		err  error
		node *TradeLog
	)
	if len(tlc.hooks) == 0 {
		if err = tlc.check(); err != nil {
			return nil, err
		}
		node, err = tlc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TradeLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tlc.check(); err != nil {
				return nil, err
			}
			tlc.mutation = mutation
			if node, err = tlc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tlc.hooks) - 1; i >= 0; i-- {
			if tlc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tlc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tlc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*TradeLog)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TradeLogMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tlc *TradeLogCreate) SaveX(ctx context.Context) *TradeLog {
	v, err := tlc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tlc *TradeLogCreate) Exec(ctx context.Context) error {
	_, err := tlc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tlc *TradeLogCreate) ExecX(ctx context.Context) {
	if err := tlc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tlc *TradeLogCreate) check() error {
	return nil
}

func (tlc *TradeLogCreate) sqlSave(ctx context.Context) (*TradeLog, error) {
	_node, _spec := tlc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tlc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (tlc *TradeLogCreate) createSpec() (*TradeLog, *sqlgraph.CreateSpec) {
	var (
		_node = &TradeLog{config: tlc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tradelog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tradelog.FieldID,
			},
		}
	)
	if id, ok := tlc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tlc.mutation.Date(); ok {
		_spec.SetField(tradelog.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := tlc.mutation.Exchange(); ok {
		_spec.SetField(tradelog.FieldExchange, field.TypeString, value)
		_node.Exchange = value
	}
	if value, ok := tlc.mutation.Ticker(); ok {
		_spec.SetField(tradelog.FieldTicker, field.TypeString, value)
		_node.Ticker = value
	}
	if value, ok := tlc.mutation.Position(); ok {
		_spec.SetField(tradelog.FieldPosition, field.TypeString, value)
		_node.Position = value
	}
	if value, ok := tlc.mutation.Strategy(); ok {
		_spec.SetField(tradelog.FieldStrategy, field.TypeString, value)
		_node.Strategy = value
	}
	if value, ok := tlc.mutation.Price(); ok {
		_spec.SetField(tradelog.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := tlc.mutation.Quantity(); ok {
		_spec.SetField(tradelog.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := tlc.mutation.Leverage(); ok {
		_spec.SetField(tradelog.FieldLeverage, field.TypeInt, value)
		_node.Leverage = value
	}
	return _node, _spec
}

// TradeLogCreateBulk is the builder for creating many TradeLog entities in bulk.
type TradeLogCreateBulk struct {
	config
	builders []*TradeLogCreate
}

// Save creates the TradeLog entities in the database.
func (tlcb *TradeLogCreateBulk) Save(ctx context.Context) ([]*TradeLog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tlcb.builders))
	nodes := make([]*TradeLog, len(tlcb.builders))
	mutators := make([]Mutator, len(tlcb.builders))
	for i := range tlcb.builders {
		func(i int, root context.Context) {
			builder := tlcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TradeLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tlcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tlcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tlcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tlcb *TradeLogCreateBulk) SaveX(ctx context.Context) []*TradeLog {
	v, err := tlcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tlcb *TradeLogCreateBulk) Exec(ctx context.Context) error {
	_, err := tlcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tlcb *TradeLogCreateBulk) ExecX(ctx context.Context) {
	if err := tlcb.Exec(ctx); err != nil {
		panic(err)
	}
}
