// Code generated by ent, DO NOT EDIT.

package profit

const (
	// Label holds the string label denoting the profit type in the database.
	Label = "profit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldProfit holds the string denoting the profit field in the database.
	FieldProfit = "profit"
	// Table holds the table name of the profit in the database.
	Table = "profit"
)

// Columns holds all SQL columns for profit fields.
var Columns = []string{
	FieldID,
	FieldDate,
	FieldProfit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
